@echo off
echo Staging changes...
git add .
echo Committing fix...
git commit -m "fix: fallback to placeholders when Supabase env variables are missing"
echo Setting remote URL to https://github.com/krishna45-ux/aspiring-adda.git...
git remote set-url origin https://github.com/krishna45-ux/aspiring-adda.git
echo Pushing to origin main (force)...
git push origin main --force
echo Done!
pause
